### ISSUE TITLE
Try now and try online does not work

### ISSUE THREAD

**Issue by AddictArts** [nvh95/vitest-preview#17]
Latest Firefox browser.

Try it now is not working. Clicking count does nothing, editing App.test.tsx does nothing new, runs the test, that is all. There is no test preview and debug does nothing. Lots of errors in the console.

```
Uncaught (in promise) Error: getTranslators: detection is already running
    at Zotero.Translate.Web.<anonymous> (translate.js:1091:45)
    at Zotero.Translate.Web.getTranslators (promise.js:36:17)
    at Object.init (inject.js:105:25)
    at Object.historyChanged (inject.js:705:21)
    at messageListener (messaging_inject.js:122:50)
    at messaging_inject.js:132:6
```

**Comment by nvh95** [comment]
Hi @AddictArts,

Thank you for spending time reporting this issue. 

> Clicking count does nothing

If you interact with the **Vitest Preview Dashboard**, it would do nothing since Vitest Preview simply takes an HTML snapshot to help engineers write and debug faster.

> There is no test preview and debug does nothing. Lots of errors in the console.

I attached here the video recording that I tried on Firefox on a Macbook, it still works fine. Can you help to provide more information like Firefox version/ your OS. If the issue is from Stackblitz, I am afraid there is not much we can do here. But if the issue persists to other users as well, we can report it back to stackblitz

https://user-images.githubusercontent.com/8603085/200762819-856baea4-9bc1-4cc8-b3f8-c56a13dcf5be.mov

**Comment by ferdicus** [comment]
@nvh95, admire your extensive, matter of fact reply to such a low effort, ill informed bug report 🙇🏿

**Comment by AddictArts** [comment]
> @nvh95, admire your extensive, matter of fact reply to such a low effort, ill informed bug report 🙇🏿

Haha, I admire the cheekyness. While matter of fact it did miss the point, of course due to me not really communicating the issue. So, I will do that now. The Gif in the main README gives the impression that the person is clicking the count and I think it is just pointing to a spot on the page, not an actual interaction. Or it is suggesting you should click. Now I can put the test code with what is happening in the gif and see it that way.

This can be closed
